version: '3.8'
services:

  # --- DB ---
  db:
    build: ./database/.
    image: guiaedu/db:1

    # volumes are not necessary
    # since data is static and is
    # loaded when container is up

    environment:
      - POSTGRES_USER=guiaedu
      - POSTGRES_PASSWORD=guiaedu
      - POSTGRES_DB=guiaedu

  # --- API ---
  api:
    build: ./buscaAPI/.
    image: guiaedu/api:1

    ports:
      - 8081:8080

    # wait for database startup
    # and retry if fail connection
    restart: on-failure
    environment:
      - SLEEP_LENGTH=5
    depends_on:
      - db

  # --- FRONT ---
  front:
    build: ./front/.
    image: guiaedu/front:1

    ports:
      - 3001:80

networks:
  default:
    name: guiaedu-network